var namespaceossia =
[
    [ "net", null, [
      [ "address_base", "classossia_1_1net_1_1address__base.html", "classossia_1_1net_1_1address__base" ],
      [ "address_data", "structossia_1_1net_1_1address__data.html", "structossia_1_1net_1_1address__data" ],
      [ "full_address_data", "structossia_1_1net_1_1full__address__data.html", "structossia_1_1net_1_1full__address__data" ],
      [ "device_capabilities", "structossia_1_1net_1_1device__capabilities.html", "structossia_1_1net_1_1device__capabilities" ],
      [ "device_base", "classossia_1_1net_1_1device__base.html", "classossia_1_1net_1_1device__base" ],
      [ "node_base", "classossia_1_1net_1_1node__base.html", "classossia_1_1net_1_1node__base" ],
      [ "instance_bounds", "structossia_1_1net_1_1instance__bounds.html", "structossia_1_1net_1_1instance__bounds" ],
      [ "protocol_base", "classossia_1_1net_1_1protocol__base.html", "classossia_1_1net_1_1protocol__base" ],
      [ "network_logger", "classossia_1_1net_1_1network__logger.html", "classossia_1_1net_1_1network__logger" ],
      [ "alias_node", "structossia_1_1net_1_1alias__node.html", "structossia_1_1net_1_1alias__node" ],
      [ "generic_address", "classossia_1_1net_1_1generic__address.html", "classossia_1_1net_1_1generic__address" ],
      [ "multiplex_protocol", "classossia_1_1net_1_1multiplex__protocol.html", "classossia_1_1net_1_1multiplex__protocol" ]
    ] ],
    [ "detail", "namespaceossia_1_1detail.html", "namespaceossia_1_1detail" ],
    [ "expressions", null, [
      [ "expression_atom", "classossia_1_1expressions_1_1expression__atom.html", "classossia_1_1expressions_1_1expression__atom" ],
      [ "expression_bool", "classossia_1_1expressions_1_1expression__bool.html", "classossia_1_1expressions_1_1expression__bool" ],
      [ "expression_composition", "classossia_1_1expressions_1_1expression__composition.html", "classossia_1_1expressions_1_1expression__composition" ],
      [ "expression_generic_base", "structossia_1_1expressions_1_1expression__generic__base.html", "structossia_1_1expressions_1_1expression__generic__base" ],
      [ "expression_not", "classossia_1_1expressions_1_1expression__not.html", "classossia_1_1expressions_1_1expression__not" ],
      [ "expression_pulse", "classossia_1_1expressions_1_1expression__pulse.html", "classossia_1_1expressions_1_1expression__pulse" ]
    ] ],
    [ "regex_path", null, [
      [ "path_element", "structossia_1_1regex__path_1_1path__element.html", "structossia_1_1regex__path_1_1path__element" ],
      [ "device", "structossia_1_1regex__path_1_1device.html", "structossia_1_1regex__path_1_1device" ],
      [ "any_instance", "structossia_1_1regex__path_1_1any__instance.html", "structossia_1_1regex__path_1_1any__instance" ],
      [ "any_between", "structossia_1_1regex__path_1_1any__between.html", "structossia_1_1regex__path_1_1any__between" ],
      [ "any_node", "structossia_1_1regex__path_1_1any__node.html", null ],
      [ "any_path", "structossia_1_1regex__path_1_1any__path.html", null ],
      [ "stop", "structossia_1_1regex__path_1_1stop.html", null ]
    ] ],
    [ "oscquery", null, [
      [ "detail", null, [
        [ "domain_to_json", "structossia_1_1oscquery_1_1detail_1_1domain__to__json.html", "structossia_1_1oscquery_1_1detail_1_1domain__to__json" ],
        [ "json_writer_impl", "structossia_1_1oscquery_1_1detail_1_1json__writer__impl.html", "structossia_1_1oscquery_1_1detail_1_1json__writer__impl" ]
      ] ],
      [ "websocket_client", "classossia_1_1oscquery_1_1websocket__client.html", "classossia_1_1oscquery_1_1websocket__client" ],
      [ "get_query_answerer", "classossia_1_1oscquery_1_1get__query__answerer.html", "classossia_1_1oscquery_1_1get__query__answerer" ],
      [ "json_parser", "structossia_1_1oscquery_1_1json__parser.html", null ],
      [ "json_query_answerer", "structossia_1_1oscquery_1_1json__query__answerer.html", "structossia_1_1oscquery_1_1json__query__answerer" ],
      [ "json_writer", "classossia_1_1oscquery_1_1json__writer.html", "classossia_1_1oscquery_1_1json__writer" ],
      [ "query_parser", "classossia_1_1oscquery_1_1query__parser.html", null ],
      [ "websocket_server", "classossia_1_1oscquery_1_1websocket__server.html", "classossia_1_1oscquery_1_1websocket__server" ],
      [ "osc_type_visitor", "structossia_1_1oscquery_1_1osc__type__visitor.html", "structossia_1_1oscquery_1_1osc__type__visitor" ],
      [ "oscquery_server_protocol", "classossia_1_1oscquery_1_1oscquery__server__protocol.html", "classossia_1_1oscquery_1_1oscquery__server__protocol" ]
    ] ],
    [ "max", null, [
      [ "box_hierachy", "classossia_1_1max_1_1box__hierachy.html", "classossia_1_1max_1_1box__hierachy" ]
    ] ],
    [ "context", "structossia_1_1context.html", "structossia_1_1context" ],
    [ "invalid_callback_error", "structossia_1_1invalid__callback__error.html", "structossia_1_1invalid__callback__error" ],
    [ "callback_container", "classossia_1_1callback__container.html", "classossia_1_1callback__container" ],
    [ "locked_container", "classossia_1_1locked__container.html", "classossia_1_1locked__container" ],
    [ "automation", "classossia_1_1automation.html", "classossia_1_1automation" ],
    [ "curve", "classossia_1_1curve.html", "classossia_1_1curve" ],
    [ "behavior", "structossia_1_1behavior.html", "structossia_1_1behavior" ],
    [ "constant_curve", "classossia_1_1constant__curve.html", "classossia_1_1constant__curve" ],
    [ "curve_abstract", "classossia_1_1curve__abstract.html", "classossia_1_1curve__abstract" ],
    [ "merger_impl", "structossia_1_1merger__impl.html", "structossia_1_1merger__impl" ],
    [ "execution_error", "structossia_1_1execution__error.html", "structossia_1_1execution__error" ],
    [ "invalid_value_type_error", "structossia_1_1invalid__value__type__error.html", "structossia_1_1invalid__value__type__error" ],
    [ "invalid_access_error", "structossia_1_1invalid__access__error.html", "structossia_1_1invalid__access__error" ],
    [ "loop", "classossia_1_1loop.html", "classossia_1_1loop" ],
    [ "mapper", "classossia_1_1mapper.html", "classossia_1_1mapper" ],
    [ "time_constraint", "classossia_1_1time__constraint.html", "classossia_1_1time__constraint" ],
    [ "time_event", "classossia_1_1time__event.html", "classossia_1_1time__event" ],
    [ "time_node", "classossia_1_1time__node.html", "classossia_1_1time__node" ],
    [ "time_process", "classossia_1_1time__process.html", "classossia_1_1time__process" ],
    [ "time_value", "structossia_1_1time__value.html", "structossia_1_1time__value" ],
    [ "custom_state", "classossia_1_1custom__state.html", "classossia_1_1custom__state" ],
    [ "message", "structossia_1_1message.html", "structossia_1_1message" ],
    [ "state", "classossia_1_1state.html", "classossia_1_1state" ],
    [ "Destination", "classossia_1_1_destination.html", "classossia_1_1_destination" ],
    [ "value", "classossia_1_1value.html", "classossia_1_1value" ],
    [ "websocket_log_sink", "structossia_1_1websocket__log__sink.html", "structossia_1_1websocket__log__sink" ],
    [ "websocket_heartbeat", "structossia_1_1websocket__heartbeat.html", "structossia_1_1websocket__heartbeat" ],
    [ "tuple_clamp", "structossia_1_1tuple__clamp.html", "structossia_1_1tuple__clamp" ],
    [ "generic_clamp", "structossia_1_1generic__clamp.html", "structossia_1_1generic__clamp" ],
    [ "domain_value_set_creation_visitor", "structossia_1_1domain__value__set__creation__visitor.html", "structossia_1_1domain__value__set__creation__visitor" ],
    [ "domain", "structossia_1_1domain.html", "structossia_1_1domain" ],
    [ "parse_error", "structossia_1_1parse__error.html", "structossia_1_1parse__error" ],
    [ "connection_error", "structossia_1_1connection__error.html", "structossia_1_1connection__error" ],
    [ "invalid_node_error", "structossia_1_1invalid__node__error.html", "structossia_1_1invalid__node__error" ],
    [ "node_not_found_error", "structossia_1_1node__not__found__error.html", "structossia_1_1node__not__found__error" ],
    [ "bad_request_error", "structossia_1_1bad__request__error.html", "structossia_1_1bad__request__error" ]
];